###
GET http://localhost:8000/products

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Celular",
    "price": 900.00
}

###
POST http://localhost:8000/products
Content-Type: application/json

{
    "name": "Notebook",
    "price": 3000.00
}